# Generated by Django 3.0 on 2019-12-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191221_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeaction',
            name='user_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
