# Generated by Django 3.0 on 2019-12-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191221_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeaction',
            name='press_like',
            field=models.BooleanField(default=False),
        ),
    ]
