# Generated by Django 3.0 on 2019-12-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=15, unique=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('project_image', models.ImageField(blank=True, upload_to='images/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('programme_language', models.CharField(blank=True, max_length=40)),
                ('update_time', models.CharField(blank=True, max_length=40)),
                ('link', models.URLField()),
                ('technologists', models.ManyToManyField(blank=True, related_name='tags', to='Resume.ImageTag')),
            ],
        ),
    ]
