# Generated by Django 3.0 on 2019-12-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetag',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
