# Generated by Django 3.0 on 2019-12-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0002_auto_20191209_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubprofile',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
