# Generated by Django 3.0 on 2019-12-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0003_auto_20191210_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='TegInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('info', models.TextField(max_length=1000)),
            ],
        ),
    ]
