# Generated by Django 3.0 on 2019-12-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0004_teginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pin',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
