# Generated by Django 3.0 on 2019-12-13 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0005_post_pin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TegInfo',
            new_name='Info',
        ),
    ]
