# Generated by Django 3.0 on 2019-12-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0006_auto_20191213_1900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GitHubProfile',
        ),
    ]
