# Generated by Django 3.0 on 2019-12-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0007_delete_githubprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=30, unique=True)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GitHubProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=30, unique=True)),
                ('link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
