# Generated by Django 3.0 on 2019-12-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0008_auto_20191213_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='email_host',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='email',
            name='email_password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='email',
            name='email_port',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='email',
            name='email_ssl',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='email',
            name='email_tls',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(blank=True, max_length=30),
        ),
    ]
