# Generated by Django 3.0 on 2019-12-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0009_auto_20191213_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=40),
        ),
    ]
