# Generated by Django 3.0 on 2020-01-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0010_auto_20191214_1651'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='GitHubProfile',
        ),
        migrations.AlterModelOptions(
            name='imagetag',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
